export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_ACCORDING_TO_COUNTRY =
  'GET_CURRENCIES_ACCORDING_TO_COUNTRY';
export const GET_CURRENCIES_START = 'GET_CURRENCIES_START';
export const CLEAR_CURRENCIES = 'CLEAR_CURRENCIES';
export const GET_DEFAULT_CURRENCIES_ERROR = 'GET_DEFAULT_CURRENCIES_ERROR';
